/*
 * CORE-ModelManager-API
 * Created by AWS Lambda
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.langframework.modelmanager.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ModelVersion
 */
public class ModelVersionTest {
    private final ModelVersion model = new ModelVersion();

    /**
     * Model tests for ModelVersion
     */
    @Test
    public void testModelVersion() {
        // TODO: test ModelVersion
    }

    /**
     * Test the property 'versionNumber'
     */
    @Test
    public void versionNumberTest() {
        // TODO: test versionNumber
    }

    /**
     * Test the property 'contextWindow'
     */
    @Test
    public void contextWindowTest() {
        // TODO: test contextWindow
    }

    /**
     * Test the property 'maxOutputTokens'
     */
    @Test
    public void maxOutputTokensTest() {
        // TODO: test maxOutputTokens
    }

    /**
     * Test the property 'trainingData'
     */
    @Test
    public void trainingDataTest() {
        // TODO: test trainingData
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

}
